name: 'HA Portal'
description: 'HA-Portal is a way to receive interactive notification in a persistent way.'
version: '1.0.5'
slug: 'ha_portal'
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ingress: true
ports:
  8099/tcp: 8099
options:
  basic_auth_username: ''
  basic_auth_password: ''
  db_username: 'homeassistant'
  db_password: ''
  db_database: 'ha'
  db_host: 'homeassistant.local'
  whitelisted_domains: '["172.30.32.2", "homeassistant.local", "0.0.0.0"]'
schema:
  basic_auth_username: str
  basic_auth_password: str
  db_username: str
  db_password: str
  db_database: str
  db_host: str
  whitelisted_domains: str
