name: 'HA Portal'
description: 'HA-Portal is a way to receive interactive notification in a persistent way.'
version: '1.0.10'
slug: 'ha_portal'
init: false
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
options:
  db_username: 'homeassistant'
  db_password: ''
  db_database: 'ha'
  db_host: 'homeassistant.local'
schema:
  db_username: str
  db_password: str
  db_database: str
  db_host: str
ports:
  5123/tcp: 8099
