name: 'Pocketbase'
description: 'Pocketbase service running on home assistant.'
version: '1.0.2'
slug: 'pocketbase'
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
ports:
  18090/tcp: 8099
